import { sendMessage } from '../lib/sendMessage.js'
const ELEMENTS = [{n:1,s:'H',name:'Hydrogène',masse:'1.008',cat:'Non-métal'},{n:2,s:'He',name:'Hélium',masse:'4.003',cat:'Gaz noble'},{n:3,s:'Li',name:'Lithium',masse:'6.941',cat:'Métal alcalin'},{n:6,s:'C',name:'Carbone',masse:'12.011',cat:'Non-métal'},{n:7,s:'N',name:'Azote',masse:'14.007',cat:'Non-métal'},{n:8,s:'O',name:'Oxygène',masse:'15.999',cat:'Non-métal'},{n:11,s:'Na',name:'Sodium',masse:'22.990',cat:'Métal alcalin'},{n:12,s:'Mg',name:'Magnésium',masse:'24.305',cat:'Métal alcalino-terreux'},{n:13,s:'Al',name:'Aluminium',masse:'26.982',cat:'Post-transition'},{n:14,s:'Si',name:'Silicium',masse:'28.086',cat:'Métalloïde'},{n:15,s:'P',name:'Phosphore',masse:'30.974',cat:'Non-métal'},{n:16,s:'S',name:'Soufre',masse:'32.065',cat:'Non-métal'},{n:17,s:'Cl',name:'Chlore',masse:'35.453',cat:'Halogène'},{n:18,s:'Ar',name:'Argon',masse:'39.948',cat:'Gaz noble'},{n:19,s:'K',name:'Potassium',masse:'39.098',cat:'Métal alcalin'},{n:20,s:'Ca',name:'Calcium',masse:'40.078',cat:'Métal alcalino-terreux'},{n:26,s:'Fe',name:'Fer',masse:'55.845',cat:'Métal de transition'},{n:29,s:'Cu',name:'Cuivre',masse:'63.546',cat:'Métal de transition'},{n:30,s:'Zn',name:'Zinc',masse:'65.38',cat:'Métal de transition'},{n:47,s:'Ag',name:'Argent',masse:'107.868',cat:'Métal de transition'},{n:79,s:'Au',name:'Or',masse:'196.967',cat:'Métal de transition'},{n:82,s:'Pb',name:'Plomb',masse:'207.2',cat:'Post-transition'},{n:92,s:'U',name:'Uranium',masse:'238.029',cat:'Actinide'},{n:78,s:'Pt',name:'Platine',masse:'195.084',cat:'Métal de transition'},{n:80,s:'Hg',name:'Mercure',masse:'200.592',cat:'Métal de transition'}]
export default async function elementaire(sock, sender, args, msg, ctx) {
  const query = args.join(' ').toLowerCase()
  if (!query) {
    const el = ELEMENTS[Math.floor(Math.random()*ELEMENTS.length)]
    return await sendMessage(sock, sender, `☩━━━〔 ⚗️ *ÉLÉMENT ALÉATOIRE* 〕━━━☩\n☠\n⛧  ${el.n} | *${el.s}* — ${el.name}\n☠  Masse: ${el.masse} u\n☩  Catégorie: ${el.cat}\n☠\n✝  Usage: ${process.env.PREFIX||'.'}elementaire <symbole/nom>\n⸸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━⸸`)
  }
  const el = ELEMENTS.find(e=>e.s.toLowerCase()===query||e.name.toLowerCase().includes(query)||e.n===parseInt(query))
  if (!el) return await sendMessage(sock, sender, `☠ Élément *${query}* introuvable.`)
  await sendMessage(sock, sender,
    `☩━━━〔 ⚗️ *TABLEAU PÉRIODIQUE* 〕━━━☩\n☠\n⛧  🔬 *${el.name}* (${el.s})\n☠\n☩  🔢 Numéro atomique: *${el.n}*\n✝  ⚖️ Masse atomique: *${el.masse} u*\n☠  📂 Catégorie: *${el.cat}*\n☠\n⸸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━⸸`)
}
